### ISSUE TITLE
"processManually" in config doesn't work when "autoProcess" set to "true"

### ISSUE THREAD

**Issue by PazzaVlad** [adonisjs/adonis-bodyparser#5]
### Brief Description
I tried stream files by following this https://adonisjs.com/docs/4.0/file-uploads docs. But it seems like     "processManually" doesn't work when "autoProcess" set to "true".

### Sample Code
Router.js:

```js
...
Route.post('upload', 'UploadController.upload')
....
```

UploadController.js
```js
...
    request.multipart.file('my-image', {}, async (file) => {
      await imageOptimizer(file.stream, file.fileName)
    })

    try {
      await request.multipart.process()
      console.log('works');
    } catch (error) {
      console.log(error);
    }
...
```

Code works correctly only if in config/bodyParser.js key autoProcess set to false (autoProcess: false)

But the same code doesn't work when:
```
autoProcess: true,
processManually: ['upload']
```
```
autoProcess: ['someurl'],
processManually: ['upload']
```

### Error Stack
```
RuntimeException: E_CANNOT_PROCESS_STREAM: Cannot process multipart stream twice. Make sure to disable files {autoProcess} when manually calling multipart.process
    at Function.invoke (/Users/vlad/Downloads/nanoparser2/node_modules/@adonisjs/generic-exceptions/src/RuntimeException.js:83:12)
    at Multipart.process (/Users/vlad/Downloads/nanoparser2/node_modules/@adonisjs/bodyparser/src/Multipart/index.js:163:49)
    at UploadController.upload (/Users/vlad/Downloads/nanoparser2/app/Controllers/Http/UploadController.js:31:31)
    at Object.method (/Users/vlad/Downloads/nanoparser2/node_modules/@adonisjs/framework/src/Server/index.js:221:18)
    at Server._resolveMiddleware (/Users/vlad/Downloads/nanoparser2/node_modules/@adonisjs/framework/src/Server/index.js:110:28)
    at _resolveListItem (/Users/vlad/Downloads/nanoparser2/node_modules/co-compose/src/Runnable.js:50:28)
    at dispatch (/Users/vlad/Downloads/nanoparser2/node_modules/co-compose/src/Runnable.js:112:16)
    at _.once (/Users/vlad/Downloads/nanoparser2/node_modules/co-compose/src/Runnable.js:111:35)
    at /Users/vlad/Downloads/nanoparser2/node_modules/lodash/lodash.js:10067:25
    at AuthInit.handle (/Users/vlad/Downloads/nanoparser2/node_modules/@adonisjs/auth/src/Middleware/AuthInit.js:46:11)
```

**Comment by antwaanvh** [comment]
It's not documented correctly in the docs, but the processManually array needs to be the exact route name as it appears in the route list, e.g:

```
processManually: ['/upload']
```

**Comment by PazzaVlad** [comment]
@antwaanvh thanks, adding slash to route.js and to UploadController.js solver the problem.

**Comment by ramsesmoreno** [comment]
> It's not documented correctly in the docs, but the processManually array needs to be the exact route name as it appears in the route list, e.g:
> 
> ```
> processManually: ['/upload']
> ```

Just to note that it may be also a dynamic route, like /upload/:id

**Comment by begueradj** [comment]
Keep in mind you need to specify within `processManually`  the route(s) name, not the endpoint(s) name.

**Comment by vimalmistry** [comment]
Can I add dynamic routes like 
`  Route.put('/posts/:postId/comment', 'CommentActionController.editComment')
`
Following config not working

` processManually: [
      '/posts/:postId/comment'
    ]`

**Comment by AlbertoPaulPopescu** [comment]
![image](https://user-images.githubusercontent.com/63293696/151246553-c5407580-1888-4355-973a-47f82637071c.png)
![image](https://user-images.githubusercontent.com/63293696/151246642-9bf4fbaf-3e42-437b-934e-dda987a8d718.png)
Just to add: if your route (ex:photos) has a prefix (ex: api) it should be added there in the processManually:['/api/photos']
